-- MySQL Script generated by MySQL Workbench
-- Thu Jun 11 10:03:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema online-library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online-library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online-library` DEFAULT CHARACTER SET utf8 ;
USE `online-library` ;

-- -----------------------------------------------------
-- Table `online-library`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-library`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(200) NULL,
  `email` VARCHAR(120) NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` LONGTEXT NOT NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online-library`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-library`.`author` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `creation_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online-library`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-library`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `creation_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online-library`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-library`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `register_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  `author_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_book_author_idx` (`author_id` ASC) VISIBLE,
  INDEX `fk_book_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `online-library`.`author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `online-library`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online-library`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-library`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(200) NULL,
  `email` VARCHAR(120) NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` LONGTEXT NOT NULL,
  `phone` CHAR(11) NULL,
  `register_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online-library`.`issued_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-library`.`issued_books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `issued_date` DATETIME NULL,
  `return_date` DATETIME NULL,
  `fine` INT NULL,
  `book_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_issued_books_book1_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_issued_books_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_issued_books_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `online-library`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issued_books_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `online-library`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
